#!/usr/bin/env python
# Quickly creates database on localhost
#
# CREATE User and DB commands
# CREATE DATABASE `$1`;
# GRANT USAGE ON * . * TO 'labrat'@'%' IDENTIFIED BY '******' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 ;
# GRANT SELECT , INSERT , UPDATE , DELETE , CREATE , DROP , INDEX , ALTER , CREATE TEMPORARY TABLES ON `labrat` . * TO 'labrat'@'%'; 
#

import sys, string, os

if __name__ == '__main__':
  usage = "%s: dbname [dbuser] [dbpass] [from_host]\n* default dnuser = dbname\n* default dbpass = dbname\n* default from_host = localhost\n"
  argcnt = len(sys.argv)
  if argcnt == 1:#Print usage if not enough args
    sys.stderr.write(usage %sys.argv[0])
    sys.exit(1)
  
  #Default dbuser and dbpass = dbname
  dbname = dbuser = dbpass = sys.argv[1]
  if argcnt > 2:
    dbuser = sys.argv[2]
  if argcnt > 3:
    dbpass = sys.argv[3]
  #Default host is localhost
  from_host = 'localhost'
  if argcnt > 4:
    from_host = sys.argv[4]

  #Creates the database, creates the dbuser, grants privs to dbuser on database
  sql_template = string.Template("CREATE DATABASE ``${dbname}``; GRANT USAGE ON * . * TO '${dbuser}'@'${from_host}' IDENTIFIED BY '${dbpass}' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0; GRANT SELECT , INSERT , UPDATE , DELETE , CREATE , DROP , INDEX , ALTER , CREATE TEMPORARY TABLES ON ``${dbname}`` . * TO '${dbuser}'@'${from_host}';")

  sqlcmd = sql_template.substitute(locals())
  os.system("mysql -u root -p --exec=\"%s\"" % sqlcmd)
